# Generated by Django 5.2.7 on 2025-12-06 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DHT', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dht11',
            name='co',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='dht11',
            name='light',
            field=models.FloatField(null=True),
        ),
    ]
